app:
  nasa:
    base-url: https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos
    api-key: DEMO_KEY

broker:
  pic-queue: nasa-pic-queue
  exchange: nasa-pic-exchange
  routing-key: nasa-pic-rk

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false